name: Build test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  analyze:
    name: Analyze code
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - run: cd lib && flutter pub get && flutter analyze
      - run: cd example && flutter pub get && flutter analyze
      - run: cd tools && flutter pub get && flutter analyze